default:
  image: openjdk:15.0.2

build-job:
  stage: build
  script:
    - ./gradlew assemble
  artifact:
    when: always
    paths:
      - build/libs/*.jar

test-job:
  stage: test
  script:
    - ./gradlew test
